var audios = [
   {
      "name":"延遲",
      "datas":[
         {
            "name":"『0.5秒』",
            "second":500,
            "id":431
         },
         {
            "name":"『1秒』",
            "second":1000,
            "id":432
         },
      ]
   },
   {
      "name":"人名",
      "datas":[
         {
            "name":"恭迎邱公建祥",
            "url":"/media/sounds/.mp3_Qvemr4N",
            "id":0
         },
         {
            "name":"哈鮭企鵝",
            "url":"/media/sounds/.mp3_7OLKGGO",
            "id":1
         },
         {
            "name":"嘎抓",
            "url":"/media/sounds/.mp3_R1pRA1t",
            "id":2
         },
         {
            "name":"兆元",
            "url":"/media/sounds/.mp3_zPEz9c6",
            "id":3
         },
         {
            "name":"小胖",
            "url":"/media/sounds/.mp3_QpwQt86",
            "id":4
         },
         {
            "name":"小胖2",
            "url":"/media/sounds/2_T68S1ZA.mp3",
            "id":5
         },
         {
            "name":"顯考邱公建祥",
            "url":"/media/sounds/.mp3_bJkmTFN",
            "id":6
         },
         {
            "name":"張兆元",
            "url":"/media/sounds/.mp3_XeWcKbg",
            "id":7
         },
         {
            "name":"邱少爺",
            "url":"/media/sounds/.mp3_ofbqNBN",
            "id":8
         },
         {
            "name":"顯考王公銘森哈鮭企鵝",
            "url":"/media/sounds/.mp3_amfgyo4",
            "id":9
         },
         {
            "name":"卓孝宣",
            "url":"/media/sounds/.mp3_qd0uQQo",
            "id":10
         },
         {
            "name":"馬老爺",
            "url":"/media/sounds/.mp3_IWq9iyu",
            "id":11
         },
         {
            "name":"邱建祥",
            "url":"/media/sounds/.mp3_s27gO7E",
            "id":12
         },
         {
            "name":"懶貓子的右拳",
            "url":"/media/sounds/.mp3_xzhhnX4",
            "id":303
         },
         {
            "name":"野獸先輩",
            "url":"/media/sounds/.mp3_MSlgXCM",
            "id":305
         },
         {
            "name":"仙界大濕",
            "url":"/media/sounds/.mp3_YB1mUiu",
            "id":306
         },
         {
            "name":"蟑螂子",
            "url":"/media/sounds/.mp3_PSt4frp",
            "id":315
         },
         {
            "name":"張公兆元",
            "url":"/media/sounds/.mp3_rRT2ll1",
            "id":362
         },
         {
            "name":"右拳",
            "url":"/media/sounds/.mp3_KonCMu6",
            "id":392
         },
         {
            "name":"顯妣陳媽卓孝宣",
            "url":"/media/sounds/.mp3_wKUdZpL",
            "id":406
         },
         {
            "name":"卓公孝宣",
            "url":"/media/sounds/.mp3_0jzYhrs",
            "id":429
         },
         {
            "name":"阿嚕桑",
            "url":"/media/sounds/.mp3_4TySudY",
            "id":436
         },
         {
            "name":"陳正義",
            "url":"/media/sounds/.mp3_giNgQMt",
            "id":449
         }
      ]
   },
   {
      "name":"升旗",
      "datas":[
         {
            "name":"主席",
            "url":"/media/sounds/.mp3_18G5w9A",
            "id":13
         },
         {
            "name":"下去啦～",
            "url":"/media/sounds/.mp3_DFdXjEP",
            "id":14
         },
         {
            "name":"哎呦～",
            "url":"/media/sounds/.mp3_QrtcPwQ",
            "id":15
         },
         {
            "name":"這就是我們的",
            "url":"/media/sounds/.mp3_8ymyDyI",
            "id":16
         },
         {
            "name":"即將啟航的時刻",
            "url":"/media/sounds/.mp3_HUEwc5Z",
            "id":17
         },
         {
            "name":"同志們",
            "url":"/media/sounds/.mp3_M7kUwsA",
            "id":18
         },
         {
            "name":"我們即將舉行升旗典禮",
            "url":"/media/sounds/.mp3_tUe2ygG",
            "id":19
         },
         {
            "name":"一柱清香",
            "url":"/media/sounds/.mp3_gxhPQkx",
            "id":20
         },
         {
            "name":"再上香",
            "url":"/media/sounds/.mp3_8RMm9J9",
            "id":21
         },
         {
            "name":"獻花獻果",
            "url":"/media/sounds/.mp3_zUXmqns",
            "id":22
         },
         {
            "name":"三柱清香罐頭塔我們送上去",
            "url":"/media/sounds/.mp3_BFReUrw",
            "id":23
         },
         {
            "name":"即將飛升為天",
            "url":"/media/sounds/.mp3_bVpSYKX",
            "id":24
         },
         {
            "name":"同志們請起立",
            "url":"/media/sounds/.mp3_ZSJifyG",
            "id":25
         },
         {
            "name":"在鞠躬的同時請脫帽",
            "url":"/media/sounds/.mp3_HfnwSCR",
            "id":26
         },
         {
            "name":"一鞠躬",
            "url":"/media/sounds/.mp3_VtDHyaY",
            "id":27
         },
         {
            "name":"再鞠躬",
            "url":"/media/sounds/.mp3_mbfQGeA",
            "id":28
         },
         {
            "name":"三鞠躬",
            "url":"/media/sounds/.mp3_Wcx0qm3",
            "id":29
         },
         {
            "name":"來賓與家屬打理",
            "url":"/media/sounds/.mp3_g2pyzTf",
            "id":30
         },
         {
            "name":"好滴",
            "url":"/media/sounds/.mp3_4F3F40v",
            "id":286
         },
         {
            "name":"同志們2",
            "url":"/media/sounds/2_Spk3Shv.mp3",
            "id":287
         },
         {
            "name":"我們",
            "url":"/media/sounds/.mp3_Syy7bZS",
            "id":288
         },
         {
            "name":"送",
            "url":"/media/sounds/.mp3_mbAoBA2",
            "id":289
         },
         {
            "name":"準備",
            "url":"/media/sounds/.mp3_jUFC1z7",
            "id":290
         },
         {
            "name":"在典禮開始的時刻",
            "url":"/media/sounds/.mp3_qrOBa8A",
            "id":291
         },
         {
            "name":"請不要喧嘩",
            "url":"/media/sounds/.mp3_MZONwyv",
            "id":292
         },
         {
            "name":"不要打鬧",
            "url":"/media/sounds/.mp3_mrUK1M9",
            "id":293
         },
         {
            "name":"敬禮～～～",
            "url":"/media/sounds/.mp3_6M8Ie8J",
            "id":294
         },
         {
            "name":"我們懷念他",
            "url":"/media/sounds/.mp3_KgMSK6R",
            "id":295
         },
         {
            "name":"我們紀念他",
            "url":"/media/sounds/.mp3_hEIiAOh",
            "id":296
         },
         {
            "name":"我們永遠想著他",
            "url":"/media/sounds/.mp3_K1a4pTg",
            "id":297
         },
         {
            "name":"典禮即將結束啦",
            "url":"/media/sounds/.mp3_0r6jmcT",
            "id":298
         },
         {
            "name":"我們要大殮蓋棺",
            "url":"/media/sounds/.mp3_x7yNVYz",
            "id":299
         },
         {
            "name":"儀式結束啦",
            "url":"/media/sounds/.mp3_HxbXTWg",
            "id":300
         },
         {
            "name":"永遠將他放在心裡面左邊的口袋",
            "url":"/media/sounds/.mp3_IedXkri",
            "id":301
         },
         {
            "name":"禮畢",
            "url":"/media/sounds/.mp3_KFQ7abU",
            "id":302
         },
         {
            "name":"升旗完畢",
            "url":"/media/sounds/.mp3_7EaSqXV",
            "id":304
         },
         {
            "name":"拿去火化",
            "url":"/media/sounds/.mp3_B5ove9S",
            "id":335
         },
         {
            "name":"請歸位",
            "url":"/media/sounds/.mp3_adLNXhs",
            "id":356
         },
         {
            "name":"非常安詳",
            "url":"/media/sounds/.mp3_wZVkfzE",
            "id":357
         },
         {
            "name":"禮畢2",
            "url":"/media/sounds/2_AL5dGY6.mp3",
            "id":366
         },
         {
            "name":"感謝",
            "url":"/media/sounds/.mp3_7UcT0RN",
            "id":367
         },
         {
            "name":"各位",
            "url":"/media/sounds/.mp3_o7Tn5pX",
            "id":368
         },
         {
            "name":"的奉獻",
            "url":"/media/sounds/.mp3_t0Wj6D3",
            "id":369
         },
         {
            "name":"的付出",
            "url":"/media/sounds/.mp3_ES48Y37",
            "id":370
         },
         {
            "name":"咱們",
            "url":"/media/sounds/.mp3_ilfwhjQ",
            "id":371
         },
         {
            "name":"黨的",
            "url":"/media/sounds/.mp3_A6XgSee",
            "id":372
         },
         {
            "name":"同志",
            "url":"/media/sounds/.mp3_Oilmle4",
            "id":373
         },
         {
            "name":"同胞",
            "url":"/media/sounds/.mp3_XyO9OTf",
            "id":374
         },
         {
            "name":"最後一程",
            "url":"/media/sounds/.mp3_7KDA4IB",
            "id":375
         },
         {
            "name":"謝謝各位",
            "url":"/media/sounds/.mp3_UucCKNd",
            "id":376
         },
         {
            "name":"升旗典禮",
            "url":"/media/sounds/.mp3_h3lW66W",
            "id":377
         },
         {
            "name":"舉行完畢",
            "url":"/media/sounds/.mp3_epkipUo",
            "id":378
         },
         {
            "name":"公祭儀式",
            "url":"/media/sounds/.mp3_FiHVGWJ",
            "id":407
         },
         {
            "name":"在儀式的舉行過程中",
            "url":"/media/sounds/.mp3_5rGr11k",
            "id":408
         },
         {
            "name":"請各位",
            "url":"/media/sounds/.mp3_IcZfwvo",
            "id":409
         },
         {
            "name":"勿喧嘩",
            "url":"/media/sounds/.mp3_uoaKFdm",
            "id":410
         },
         {
            "name":"勿吵鬧",
            "url":"/media/sounds/.mp3_X8u5RxF",
            "id":411
         },
         {
            "name":"勿移動",
            "url":"/media/sounds/.mp3_WDu3MHl",
            "id":412
         },
         {
            "name":"上香",
            "url":"/media/sounds/.mp3_QPbJgDB",
            "id":413
         },
         {
            "name":"中華民族",
            "url":"/media/sounds/.mp3_WQ31RDz",
            "id":414
         },
         {
            "name":"他是",
            "url":"/media/sounds/.mp3_XeekGVc",
            "id":415
         },
         {
            "name":"咱們的",
            "url":"/media/sounds/.mp3_MGkR6yA",
            "id":416
         },
         {
            "name":"他的",
            "url":"/media/sounds/.mp3_JNP1XTV",
            "id":417
         },
         {
            "name":"英勇奉獻",
            "url":"/media/sounds/.mp3_QIajtsq",
            "id":418
         },
         {
            "name":"請出外面大堂的時候",
            "url":"/media/sounds/.mp3_4Asl1dj",
            "id":419
         },
         {
            "name":"用淨水浮水洗滌一下身心",
            "url":"/media/sounds/.mp3_q0ouzIW",
            "id":420
         },
         {
            "name":"請復帽",
            "url":"/media/sounds/.mp3_ntZpA4K",
            "id":421
         },
         {
            "name":"謝謝各位的到來",
            "url":"/media/sounds/.mp3_5A3tknn",
            "id":422
         },
         {
            "name":"廁所在左邊",
            "url":"/media/sounds/.mp3_eFaSeeq",
            "id":423
         },
         {
            "name":"入口在右邊",
            "url":"/media/sounds/.mp3_RbLWqkr",
            "id":424
         },
         {
            "name":"停車場在中間",
            "url":"/media/sounds/.mp3_F02ZqDm",
            "id":425
         },
         {
            "name":"記得要過檻",
            "url":"/media/sounds/.mp3_DVZbptz",
            "id":426
         },
         {
            "name":"祝他",
            "url":"/media/sounds/.mp3_rjt52Ne",
            "id":430
         },
         {
            "name":"我們即將舉行",
            "url":"/media/sounds/.mp3_SeGYdC7",
            "id":433
         },
         {
            "name":"你下去的真是漂亮",
            "url":"/media/sounds/.mp3_AHZqWTc",
            "id":465
         },
         {
            "name":"一路好走",
            "url":"/media/sounds/.mp3_jC8Fgjv",
            "id":466
         },
         {
            "name":"不要亂跑亂跳",
            "url":"/media/sounds/.mp3_8rHVlwF",
            "id":467
         },
         {
            "name":"火化完成",
            "url":"/media/sounds/.mp3_zH58kiP",
            "id":468
         },
         {
            "name":"他的灰有點臭",
            "url":"/media/sounds/.mp3_93fNFe9",
            "id":469
         },
         {
            "name":"我們現在即將舉行懲罰典禮",
            "url":"/media/sounds/.mp3_71rKymJ",
            "id":470
         },
         {
            "name":"典禮即將開始",
            "url":"/media/sounds/.mp3_APHhRNE",
            "id":471
         },
         {
            "name":"畢竟本人就很臭",
            "url":"/media/sounds/.mp3_vnNZtdC",
            "id":472
         },
         {
            "name":"準備2",
            "url":"/media/sounds/2_AK5O24Y.mp3",
            "id":473
         },
         {
            "name":"請家屬來認領",
            "url":"/media/sounds/.mp3_Mw5TSle",
            "id":474
         },
         {
            "name":"請豎立",
            "url":"/media/sounds/.mp3_RrGctTm",
            "id":475
         }
      ]
   },
   {
      "name":"罵人",
      "datas":[
         {
            "name":"屌你老母",
            "url":"/media/sounds/.mp3_MGgvnBc",
            "id":31
         },
         {
            "name":"看你娘",
            "url":"/media/sounds/.mp3_8dRNI8f",
            "id":32
         },
         {
            "name":"甲洨喔～",
            "url":"/media/sounds/.mp3_sezrMNa",
            "id":33
         },
         {
            "name":"靠杯喔",
            "url":"/media/sounds/.mp3_KE0u1go",
            "id":34
         },
         {
            "name":"欠我幹啊？是不是？",
            "url":"/media/sounds/.mp3_iCm5mfD",
            "id":35
         },
         {
            "name":"幹死他！",
            "url":"/media/sounds/.mp3_V90v3Uz",
            "id":36
         },
         {
            "name":"他死定了他",
            "url":"/media/sounds/.mp3_NNeVbQx",
            "id":37
         },
         {
            "name":"王八蛋",
            "url":"/media/sounds/.mp3_u5GyBfE",
            "id":38
         },
         {
            "name":"揍死你",
            "url":"/media/sounds/.mp3_eeRpk5h",
            "id":39
         },
         {
            "name":"你倒大楣了",
            "url":"/media/sounds/.mp3_k42Ebs9",
            "id":40
         },
         {
            "name":"你怎麼不下去啊？",
            "url":"/media/sounds/.mp3_ymzeXkq",
            "id":41
         },
         {
            "name":"你倒霉了",
            "url":"/media/sounds/.mp3_i7hzaxU",
            "id":42
         },
         {
            "name":"我沒有去幹他，我他媽不姓張！",
            "url":"/media/sounds/.mp3_EMspCZe",
            "id":43
         },
         {
            "name":"幹你娘機掰",
            "url":"/media/sounds/g8.mp3",
            "id":44
         },
         {
            "name":"你有膽別跑幹你娘",
            "url":"/media/sounds/.mp3_Fr0dhay",
            "id":45
         },
         {
            "name":"操你媽啦",
            "url":"/media/sounds/.mp3_Q59LwK6",
            "id":46
         },
         {
            "name":"智障",
            "url":"/media/sounds/.mp3_GVdHujG",
            "id":47
         },
         {
            "name":"你媽死了",
            "url":"/media/sounds/nmsl.mp3",
            "id":48
         },
         {
            "name":"操你媽你叫誰啊",
            "url":"/media/sounds/.mp3_k7tgJCg",
            "id":49
         },
         {
            "name":"你怎麼死這麼慘？",
            "url":"/media/sounds/.mp3_V2jHYfc",
            "id":311
         },
         {
            "name":"你怎麼變成這樣？",
            "url":"/media/sounds/.mp3_ZuGwVEc",
            "id":312
         },
         {
            "name":"你怎麼變得像屎啊？",
            "url":"/media/sounds/.mp3_NiPntCg",
            "id":313
         },
         {
            "name":"你在嗆三小？",
            "url":"/media/sounds/.mp3_mDzJINu",
            "id":319
         },
         {
            "name":"屌嗆你一波",
            "url":"/media/sounds/.mp3_SmvJbIV",
            "id":320
         },
         {
            "name":"嗆你祖宗十八代",
            "url":"/media/sounds/.mp3_xNvLqTH",
            "id":321
         },
         {
            "name":"嗆到你爸媽認不出你是誰",
            "url":"/media/sounds/.mp3_ruxFmG4",
            "id":322
         },
         {
            "name":"機掰",
            "url":"/media/sounds/.mp3_SKfvLn4",
            "id":323
         },
         {
            "name":"你是不是真的想被我送下去？",
            "url":"/media/sounds/.mp3_P1ONGPc",
            "id":316
         },
         {
            "name":"欠我插是不是啊？",
            "url":"/media/sounds/.mp3_iE3179c",
            "id":361
         },
         {
            "name":"媽的哩",
            "url":"/media/sounds/.mp3_oMrTqx3",
            "id":493
         }
      ]
   },
   {
      "name":"叫聲",
      "datas":[
         {
            "name":"兆元高潮",
            "url":"/media/sounds/mp3cut_J0M19Kg.mp3",
            "id":50
         },
         {
            "name":"兆元高潮2",
            "url":"/media/sounds/.mp3_t3U7oFv",
            "id":51
         },
         {
            "name":"啊啊",
            "url":"/media/sounds/at88-cm-626466910-online-audio-converter-mp3cut.mp3",
            "id":52
         },
         {
            "name":"大濕嗩吶",
            "url":"/media/sounds/.mp3_pybTdjJ",
            "id":53
         },
         {
            "name":"汪",
            "url":"/media/sounds/.mp3_EBZyT3o",
            "id":54
         },
         {
            "name":"啊➚啊➚啊➚",
            "url":"/media/sounds/.mp3_kk0OzW9",
            "id":55
         },
         {
            "name":"埃～",
            "url":"/media/sounds/.mp3_f0EkltN",
            "id":56
         },
         {
            "name":"啵",
            "url":"/media/sounds/.mp3_MCgCt03",
            "id":57
         },
         {
            "name":"兆元的不明叫聲",
            "url":"/media/sounds/.mp3_bZZt709",
            "id":58
         },
         {
            "name":"兆元的不明叫聲2",
            "url":"/media/sounds/2_9UROs2b.mp3",
            "id":59
         },
         {
            "name":"啊～～～",
            "url":"/media/sounds/3_3aTyHtk.mp3",
            "id":60
         },
         {
            "name":"哇～",
            "url":"/media/sounds/.mp3_r3mRO9r",
            "id":61
         },
         {
            "name":"哇～～～",
            "url":"/media/sounds/.mp3_doUTf46",
            "id":62
         },
         {
            "name":"噢～～～",
            "url":"/media/sounds/.mp3_Yp43o6F",
            "id":63
         },
         {
            "name":"诶嘿～",
            "url":"/media/sounds/.mp3_LnaCDvj",
            "id":64
         },
         {
            "name":"嘿嘿",
            "url":"/media/sounds/.mp3_WfYbRzx",
            "id":363
         },
         {
            "name":"啊！啊！啊！",
            "url":"/media/sounds/.mp3_xFi72qk",
            "id":381
         },
         {
            "name":"兆元不明叫聲3",
            "url":"/media/sounds/3_4qRaYw2.mp3",
            "id":382
         }
      ]
   },
   {
      "name":"哭",
      "datas":[
         {
            "name":"元元子哭哭",
            "url":"/media/sounds/.mp3_vJDMfn5",
            "id":65
         },
         {
            "name":"元元子哭哭２",
            "url":"/media/sounds/2_qVIr1cb.mp3",
            "id":66
         },
         {
            "name":"嗚嗚嗚嗚嗚",
            "url":"/media/sounds/.mp3_62LU6K6",
            "id":67
         }
      ]
   },
   {
      "name":"小安",
      "datas":[
         {
            "name":"大家好，我是小安",
            "url":"/media/sounds/.mp3_cGYB7q3",
            "id":68
         },
         {
            "name":"我喜歡拉小提琴跳舞還有唱歌",
            "url":"/media/sounds/.mp3_0pHzSH8",
            "id":69
         },
         {
            "name":"如果喜歡歡迎來我的頻道",
            "url":"/media/sounds/.mp3_BbdP5Vn",
            "id":70
         },
         {
            "name":"大家好，我是小安2",
            "url":"/media/sounds/2_I1PIf8z.mp3",
            "id":443
         }
      ]
   },
   {
      "name":"甲",
      "datas":[
         {
            "name":"幫他吸",
            "url":"/media/sounds/.mp3_XPMZXvO",
            "id":71
         },
         {
            "name":"蛤？乖乖站好啊！",
            "url":"/media/sounds/.mp3_6UcD4DW",
            "id":72
         },
         {
            "name":"又爽又舒服",
            "url":"/media/sounds/.mp3_GfRcuqk",
            "id":73
         },
         {
            "name":"衛浴設備",
            "url":"/media/sounds/.mp3_AQvH48g",
            "id":74
         },
         {
            "name":"只能在廁所",
            "url":"/media/sounds/.mp3_A4JmahD",
            "id":75
         },
         {
            "name":"馬桶",
            "url":"/media/sounds/.mp3_x7WYWqD",
            "id":76
         },
         {
            "name":"便器",
            "url":"/media/sounds/.mp3_aULw6kz",
            "id":77
         },
         {
            "name":"你們是Gay嗎？",
            "url":"/media/sounds/gay_hZMqOfW.mp3",
            "id":78
         },
         {
            "name":"我的台是Gay台",
            "url":"/media/sounds/gay_pnsVDVF.mp3",
            "id":79
         },
         {
            "name":"屁股人人有份",
            "url":"/media/sounds/.mp3_zcIbDje",
            "id":80
         },
         {
            "name":"禮到人到屁眼也到",
            "url":"/media/sounds/.mp3_JLFfEjh",
            "id":81
         },
         {
            "name":"幹到你屁眼流湯",
            "url":"/media/sounds/.mp3_7YZwjSV",
            "id":82
         },
         {
            "name":"等等來肛吧！",
            "url":"/media/sounds/.mp3_xgnrGrJ",
            "id":83
         },
         {
            "name":"屁眼故障來找我",
            "url":"/media/sounds/.mp3_MGfOnQ8",
            "id":84
         },
         {
            "name":"又粗又大又壯",
            "url":"/media/sounds/.mp3_pJiizp4",
            "id":85
         },
         {
            "name":"GayBar最佳員工",
            "url":"/media/sounds/gay-bar-mp3cut.mp3",
            "id":86
         },
         {
            "name":"正義比我大",
            "url":"/media/sounds/dfpid-lteg0-mp3cut.mp3",
            "id":87
         },
         {
            "name":"現在跟我已經特殊性關西了啦",
            "url":"/media/sounds/.mp3_m8XKsXq",
            "id":88
         },
         {
            "name":"你來當我男朋友好不好？",
            "url":"/media/sounds/.mp3_o0zKQGG",
            "id":89
         },
         {
            "name":"大大的",
            "url":"/media/sounds/.mp3_7iiP4Lt",
            "id":90
         },
         {
            "name":"更好用",
            "url":"/media/sounds/vid16109065234758.mp3",
            "id":91
         },
         {
            "name":"等你發現",
            "url":"/media/sounds/video-16109063368958.mp3",
            "id":92
         },
         {
            "name":"太大了",
            "url":"/media/sounds/.mp3_PFCfAH7",
            "id":93
         },
         {
            "name":"気持ちいい～～",
            "url":"/media/sounds/.mp3_Bg92T2V",
            "id":94
         },
         {
            "name":"小雞雞！",
            "url":"/media/sounds/.mp3_QD0ed1q",
            "id":95
         },
         {
            "name":"我愛的是皮卡屁",
            "url":"/media/sounds/.mp3_dHKsEEW",
            "id":96
         },
         {
            "name":"打手槍",
            "url":"/media/sounds/.mp3_zThDx90",
            "id":97
         },
         {
            "name":"臀部誘人的曲線",
            "url":"/media/sounds/.mp3_zd4cwBd",
            "id":98
         },
         {
            "name":"一見鐘情",
            "url":"/media/sounds/.mp3_3iMr8BA",
            "id":99
         },
         {
            "name":"怎麼有東西黏黏的？",
            "url":"/media/sounds/.mp3_fXLtaS5",
            "id":101
         },
         {
            "name":"いたい いたい",
            "url":"/media/sounds/.mp3_2v23bZN",
            "id":102
         },
         {
            "name":"屁眼",
            "url":"/media/sounds/.mp3_hD5HaDb",
            "id":165
         },
         {
            "name":"幹下去",
            "url":"/media/sounds/.mp3_unAGHUQ",
            "id":308
         },
         {
            "name":"沒穿褲子",
            "url":"/media/sounds/.mp3_lzS6h3R",
            "id":318
         },
         {
            "name":"放閃",
            "url":"/media/sounds/.mp3_2TPDG2I",
            "id":326
         },
         {
            "name":"結婚",
            "url":"/media/sounds/.mp3_EyKmg91",
            "id":327
         },
         {
            "name":"老婆",
            "url":"/media/sounds/.mp3_DZLy6Rt",
            "id":330
         },
         {
            "name":"跟你回家吧",
            "url":"/media/sounds/.mp3_Nm8yMqM",
            "id":332
         },
         {
            "name":"我肛你",
            "url":"/media/sounds/.mp3_eZTwbId",
            "id":333
         },
         {
            "name":"你給我肛",
            "url":"/media/sounds/.mp3_IacAC2X",
            "id":334
         },
         {
            "name":"肉便器",
            "url":"/media/sounds/.mp3_0xnrHH9",
            "id":337
         },
         {
            "name":"你怎麼那麼喜歡找我？",
            "url":"/media/sounds/.mp3_o6IKokN",
            "id":338
         },
         {
            "name":"我就再也不會感到寂寞了",
            "url":"/media/sounds/.mp3_QmkZchP",
            "id":339
         },
         {
            "name":"就只有你能讓我滿足",
            "url":"/media/sounds/.mp3_tjsjuE2",
            "id":340
         },
         {
            "name":"來一發",
            "url":"/media/sounds/.mp3_88EkzCX",
            "id":349
         },
         {
            "name":"褲子掉了",
            "url":"/media/sounds/.mp3_hbC2zKz",
            "id":350
         },
         {
            "name":"白白又濃又稠",
            "url":"/media/sounds/.mp3_0TtTqCJ",
            "id":351
         },
         {
            "name":"積了很久",
            "url":"/media/sounds/.mp3_I5kV9JX",
            "id":352
         },
         {
            "name":"整個被弄到壞掉",
            "url":"/media/sounds/.mp3_YUmUUGd",
            "id":358
         },
         {
            "name":"Gay",
            "url":"/media/sounds/gay_TuQLa0l.mp3",
            "id":400
         },
         {
            "name":"兆元的形狀",
            "url":"/media/sounds/.mp3_aW0aCSa",
            "id":402
         },
         {
            "name":"肉便器2",
            "url":"/media/sounds/2_ypisYig.mp3",
            "id":405
         },
         {
            "name":"肉便器3",
            "url":"/media/sounds/3_W6JFew9.mp3",
            "id":427
         },
         {
            "name":"節操",
            "url":"/media/sounds/.mp3_6UzYNIf",
            "id":428
         },
         {
            "name":"わかてる",
            "url":"/media/sounds/.mp3_qEO8MmK",
            "id":439
         },
         {
            "name":"愛してる",
            "url":"/media/sounds/.mp3_4GsYrdL",
            "id":440
         },
         {
            "name":"大大大大好き",
            "url":"/media/sounds/.mp3_wCSPVHP",
            "id":441
         },
         {
            "name":"あいくいくいくいく",
            "url":"/media/sounds/.mp3_X6NzJKZ",
            "id":442
         },
         {
            "name":"通馬桶",
            "url":"/media/sounds/.mp3_ik2Pghw",
            "id":446
         },
         {
            "name":"通屁眼",
            "url":"/media/sounds/.mp3_ayEIcv8",
            "id":447
         },
         {
            "name":"跟我通看看",
            "url":"/media/sounds/.mp3_0JW37R0",
            "id":448
         },
         {
            "name":"喇舌",
            "url":"/media/sounds/.mp3_VZ89Gnn",
            "id":451
         },
         {
            "name":"屁眼夾緊",
            "url":"/media/sounds/.mp3_Royf3tZ",
            "id":453
         },
         {
            "name":"屁眼都爛了",
            "url":"/media/sounds/.mp3_qaclwLx",
            "id":454
         },
         {
            "name":"吸允聲",
            "url":"/media/sounds/.mp3_xHrVmhx",
            "id":455
         },
         {
            "name":"真會吸啊",
            "url":"/media/sounds/.mp3_PB9SoMc",
            "id":456
         },
         {
            "name":"Gay片",
            "url":"/media/sounds/gay_kYnGpBO.mp3",
            "id":476
         },
         {
            "name":"又大",
            "url":"/media/sounds/.mp3_uT0r28i",
            "id":477
         },
         {
            "name":"又粗",
            "url":"/media/sounds/.mp3_9XjJVOm",
            "id":478
         },
         {
            "name":"又硬",
            "url":"/media/sounds/.mp3_uW2x0TF",
            "id":479
         },
         {
            "name":"在我後面",
            "url":"/media/sounds/.mp3_zfX9nH0",
            "id":480
         },
         {
            "name":"含自己的",
            "url":"/media/sounds/.mp3_tqGvcI8",
            "id":481
         },
         {
            "name":"我都是被肛的",
            "url":"/media/sounds/.mp3_QPuJiEx",
            "id":482
         },
         {
            "name":"男的我更愛",
            "url":"/media/sounds/.mp3_ZIhlFOG",
            "id":483
         },
         {
            "name":"啪著我",
            "url":"/media/sounds/.mp3_VYwWyzU",
            "id":484
         },
         {
            "name":"您打啊",
            "url":"/media/sounds/.mp3_SZTuA0H",
            "id":485
         },
         {
            "name":"粗粗的",
            "url":"/media/sounds/.mp3_LLyXTTv",
            "id":486
         },
         {
            "name":"軟軟的",
            "url":"/media/sounds/.mp3_HUFgdAn",
            "id":487
         },
         {
            "name":"短短的",
            "url":"/media/sounds/.mp3_QtmhloI",
            "id":488
         },
         {
            "name":"幫你含",
            "url":"/media/sounds/.mp3_ltn4eAc",
            "id":489
         }
      ]
   },
   {
      "name":"你是我的屁眼",
      "datas":[
         {
            "name":"你是我的屁眼～",
            "url":"/media/sounds/.mp3_YlLzldc",
            "id":100
         },
         {
            "name":"你是我的屁眼2",
            "url":"/media/sounds/2_0l7Ur8W.mp3",
            "id":490
         },
         {
            "name":"帶我穿越右拳的直腸",
            "url":"/media/sounds/.mp3_9ceA49V",
            "id":491
         },
         {
            "name":"帶我領略四季的建祥",
            "url":"/media/sounds/.mp3_u28yOko",
            "id":492
         }
      ],
   },
   {
      "name":"其他",
      "datas":[
         {
            "name":"兆元你跪啊",
            "url":"/media/sounds/r_qgSILAC.mp3",
            "id":103
         },
         {
            "name":"我長得像盤子嗎",
            "url":"/media/sounds/mp3cut_GOBcLPW.mp3",
            "id":104
         },
         {
            "name":"男的幹",
            "url":"/media/sounds/nxx4t-vgzoo-mp3cut.mp3",
            "id":105
         },
         {
            "name":"好牛逼",
            "url":"/media/sounds/-firefox-nightly-2021-01-03-23-22-20-online-audio-converter-mp3cut.mp3",
            "id":106
         },
         {
            "name":"這...這什麼啊？",
            "url":"/media/sounds/.mp3_pwhUoDX",
            "id":107
         },
         {
            "name":"安安啊",
            "url":"/media/sounds/.mp3_Eiqk86r",
            "id":108
         },
         {
            "name":"來來來來來",
            "url":"/media/sounds/.mp3_xycGHnl",
            "id":109
         },
         {
            "name":"讓我看看",
            "url":"/media/sounds/.mp3_6Lqc3Qq",
            "id":110
         },
         {
            "name":"這真的可以做嗎？",
            "url":"/media/sounds/.mp3_4cS8Sjt",
            "id":111
         },
         {
            "name":"可以拉！沒問題啦！",
            "url":"/media/sounds/.mp3_J2YmRnC",
            "id":112
         },
         {
            "name":"や...やります！",
            "url":"/media/sounds/.mp3_QvZxuRG",
            "id":113
         },
         {
            "name":"這個房間",
            "url":"/media/sounds/.mp3_rwLYEP1",
            "id":114
         },
         {
            "name":"把門推開",
            "url":"/media/sounds/.mp3_H7oPwCo",
            "id":115
         },
         {
            "name":"亮亮的",
            "url":"/media/sounds/.mp3_QqnYLgm",
            "id":116
         },
         {
            "name":"真的要做嗎？",
            "url":"/media/sounds/.mp3_ZnEfHCY",
            "id":117
         },
         {
            "name":"你就做嘛！",
            "url":"/media/sounds/.mp3_j0R7stG",
            "id":118
         },
         {
            "name":"我回來啦！",
            "url":"/media/sounds/.mp3_wv5adop",
            "id":119
         },
         {
            "name":"到底是誰啦！",
            "url":"/media/sounds/.mp3_SNombcN",
            "id":120
         },
         {
            "name":"奇奇怪怪的",
            "url":"/media/sounds/id.mp3",
            "id":121
         },
         {
            "name":"變成大濕的形狀",
            "url":"/media/sounds/.mp3_GQGZwUg",
            "id":122
         },
         {
            "name":"按個讚",
            "url":"/media/sounds/.mp3_YMbw2s3",
            "id":123
         },
         {
            "name":"好可愛",
            "url":"/media/sounds/.mp3_0G9BCcf",
            "id":124
         },
         {
            "name":"好可愛喔～",
            "url":"/media/sounds/.mp3_FyLcYAA",
            "id":125
         },
         {
            "name":"車車",
            "url":"/media/sounds/.mp3_kKb2hld",
            "id":126
         },
         {
            "name":"戴綠帽",
            "url":"/media/sounds/.mp3_Yp1yG0w",
            "id":127
         },
         {
            "name":"不要幫我上香好嗎",
            "url":"/media/sounds/.mp3_nHwnfUq",
            "id":128
         },
         {
            "name":"PEKO",
            "url":"/media/sounds/peko_xlI32l1.mp3",
            "id":129
         },
         {
            "name":"我不知道",
            "url":"/media/sounds/.mp3_RARH3jm",
            "id":130
         },
         {
            "name":"那是什麼？",
            "url":"/media/sounds/.mp3_INOHvjM",
            "id":131
         },
         {
            "name":"我都不看這些的！",
            "url":"/media/sounds/.mp3_ghqhh7X",
            "id":132
         },
         {
            "name":"你餓了嗎？",
            "url":"/media/sounds/.mp3_V21onQI",
            "id":133
         },
         {
            "name":"給你吃點好吃的呦～",
            "url":"/media/sounds/.mp3_jgiFfID",
            "id":134
         },
         {
            "name":"什...什麼好吃的啊？",
            "url":"/media/sounds/.mp3_KPnGSI6",
            "id":135
         },
         {
            "name":"來啦！",
            "url":"/media/sounds/.mp3_EnLFMnS",
            "id":136
         },
         {
            "name":"拿...拿都拿！",
            "url":"/media/sounds/.mp3_SaVFyQg",
            "id":137
         },
         {
            "name":"元元要上車嗎？",
            "url":"/media/sounds/.mp3_OU5n2sn",
            "id":138
         },
         {
            "name":"不要了不要了不好意思不要了",
            "url":"/media/sounds/.mp3_n1abJfx",
            "id":139
         },
         {
            "name":"怕～",
            "url":"/media/sounds/.mp3_vv9syGt",
            "id":140
         },
         {
            "name":"獅子頭",
            "url":"/media/sounds/.mp3_8fd17HU",
            "id":141
         },
         {
            "name":"不要吵啊",
            "url":"/media/sounds/.mp3_p4StLDQ",
            "id":142
         },
         {
            "name":"等一下看了我就下去了",
            "url":"/media/sounds/.mp3_6ORMLw3",
            "id":143
         },
         {
            "name":"他在盯著我",
            "url":"/media/sounds/.mp3_GAXIdak",
            "id":144
         },
         {
            "name":"沒事沒事",
            "url":"/media/sounds/.mp3_dAnfP2k",
            "id":145
         },
         {
            "name":"我愛你",
            "url":"/media/sounds/.mp3_tD9ZK1A",
            "id":146
         },
         {
            "name":"咳瘦",
            "url":"/media/sounds/.mp3_bq1VpCh",
            "id":147
         },
         {
            "name":"是中邪了嗎？",
            "url":"/media/sounds/.mp3_ayGRwhA",
            "id":148
         },
         {
            "name":"是生病了",
            "url":"/media/sounds/.mp3_kFELYPV",
            "id":149
         },
         {
            "name":"變態",
            "url":"/media/sounds/.mp3_KFKQRfx",
            "id":150
         },
         {
            "name":"喂！",
            "url":"/media/sounds/.mp3_3KObnZ5",
            "id":151
         },
         {
            "name":"騎這麼快啊！",
            "url":"/media/sounds/.mp3_ci6BQit",
            "id":152
         },
         {
            "name":"被拖下去",
            "url":"/media/sounds/.mp3_XKnCheF",
            "id":153
         },
         {
            "name":"下車！",
            "url":"/media/sounds/.mp3_6XPkhEo",
            "id":154
         },
         {
            "name":"幹有這麼誇張的喔？",
            "url":"/media/sounds/.mp3_KE7boCw",
            "id":155
         },
         {
            "name":"哇幹！",
            "url":"/media/sounds/.mp3_rNYrWjw",
            "id":156
         },
         {
            "name":"真的要娶她了",
            "url":"/media/sounds/.mp3_mFo2yIu",
            "id":157
         },
         {
            "name":"好啦！",
            "url":"/media/sounds/.mp3_8twO2e8",
            "id":158
         },
         {
            "name":"決定了！",
            "url":"/media/sounds/.mp3_ziWarO0",
            "id":159
         },
         {
            "name":"辦婚禮了！",
            "url":"/media/sounds/.mp3_EwlEmLo",
            "id":160
         },
         {
            "name":"等著收我喜帖吧！",
            "url":"/media/sounds/.mp3_zGLOhn2",
            "id":161
         },
         {
            "name":"進入",
            "url":"/media/sounds/.mp3_UvcrPxx",
            "id":162
         },
         {
            "name":"鬼故事",
            "url":"/media/sounds/.mp3_cNcJ0vj",
            "id":163
         },
         {
            "name":"哭啊",
            "url":"/media/sounds/.mp3_0GIqxTc",
            "id":164
         },
         {
            "name":"打開",
            "url":"/media/sounds/.mp3_RKWPHrR",
            "id":166
         },
         {
            "name":"為什麼是我的照片啊？",
            "url":"/media/sounds/.mp3_5zM5Wb0",
            "id":167
         },
         {
            "name":"厚呦又我",
            "url":"/media/sounds/.mp3_2expFUH",
            "id":168
         },
         {
            "name":"我要穿女裝",
            "url":"/media/sounds/.mp3_lus3V2U",
            "id":169
         },
         {
            "name":"衝了啦！",
            "url":"/media/sounds/.mp3_BfkAnRw",
            "id":170
         },
         {
            "name":"等一下",
            "url":"/media/sounds/.mp3_4wuO8Po",
            "id":171
         },
         {
            "name":"我不要！",
            "url":"/media/sounds/.mp3_7CVITIL",
            "id":172
         },
         {
            "name":"我好害怕",
            "url":"/media/sounds/.mp3_soEoCey",
            "id":173
         },
         {
            "name":"你就是我的妖豔賤貨",
            "url":"/media/sounds/.mp3_TKruUWZ",
            "id":174
         },
         {
            "name":"NO~~~",
            "url":"/media/sounds/no_hDCn8Pd.mp3",
            "id":175
         },
         {
            "name":"救我！",
            "url":"/media/sounds/.mp3_FpU85TY",
            "id":176
         },
         {
            "name":"龍潭廁所子",
            "url":"/media/sounds/.mp3_XBxAuQE",
            "id":177
         },
         {
            "name":"因該不會上車吧？",
            "url":"/media/sounds/.mp3_gbOQFSy",
            "id":178
         },
         {
            "name":"埃！埃！等一下等一下",
            "url":"/media/sounds/.mp3_DPvR6oE",
            "id":179
         },
         {
            "name":"嚇我一跳",
            "url":"/media/sounds/.mp3_17doqeq",
            "id":180
         },
         {
            "name":"呵呵！肥宅",
            "url":"/media/sounds/.mp3_3q4GehY",
            "id":181
         },
         {
            "name":"這不是我的衣服嗎？",
            "url":"/media/sounds/.mp3_tySaZ0Z",
            "id":182
         },
         {
            "name":"我好變那個肥宅",
            "url":"/media/sounds/.mp3_rrlF10B",
            "id":183
         },
         {
            "name":"我不想聽拜託不要告述我",
            "url":"/media/sounds/.mp3_vMfjpaV",
            "id":184
         },
         {
            "name":"我看你是很勇喔",
            "url":"/media/sounds/.mp3_AjtIw7J",
            "id":185
         },
         {
            "name":"你這個",
            "url":"/media/sounds/.mp3_v5SOpJW",
            "id":186
         },
         {
            "name":"NTR",
            "url":"/media/sounds/ntr.mp3",
            "id":187
         },
         {
            "name":"睡的真飽",
            "url":"/media/sounds/.mp3_MYL9vjd",
            "id":188
         },
         {
            "name":"怎麼那麼垃圾啊？",
            "url":"/media/sounds/.mp3_R15bTw4",
            "id":189
         },
         {
            "name":"什麼狀況？",
            "url":"/media/sounds/.mp3_n6fcv2s",
            "id":190
         },
         {
            "name":"不對啊",
            "url":"/media/sounds/.mp3_c3lKHdc",
            "id":191
         },
         {
            "name":"我哪是",
            "url":"/media/sounds/.mp3_AGeXdRj",
            "id":192
         },
         {
            "name":"我明明就是",
            "url":"/media/sounds/.mp3_30fUzjw",
            "id":193
         },
         {
            "name":"肥宅",
            "url":"/media/sounds/.mp3_g06gcfv",
            "id":194
         },
         {
            "name":"好色喔～",
            "url":"/media/sounds/.mp3_sQ6DrCY",
            "id":195
         },
         {
            "name":"啊！好香喔～",
            "url":"/media/sounds/.mp3_k9r6Iiu",
            "id":196
         },
         {
            "name":"怎麼那麼臭啊？",
            "url":"/media/sounds/.mp3_Bk1XvKF",
            "id":197
         },
         {
            "name":"我有這麼爛嗎？",
            "url":"/media/sounds/.mp3_EouyLCw",
            "id":198
         },
         {
            "name":"我要放屁了喔！",
            "url":"/media/sounds/.mp3_BodBvvP",
            "id":199
         },
         {
            "name":"盤子們",
            "url":"/media/sounds/.mp3_t3OdqKw",
            "id":200
         },
         {
            "name":"駕到啦～",
            "url":"/media/sounds/.mp3_WVK2kgt",
            "id":201
         },
         {
            "name":"乾我屁事啊？",
            "url":"/media/sounds/.mp3_HkNRBpr",
            "id":202
         },
         {
            "name":"好康的呦～",
            "url":"/media/sounds/.mp3_4xdu00P",
            "id":203
         },
         {
            "name":"哎呀～比遊戲還刺激～",
            "url":"/media/sounds/.mp3_ygUHrD1",
            "id":204
         },
         {
            "name":"自慰行助理",
            "url":"/media/sounds/.mp3_GDLviK8",
            "id":205
         },
         {
            "name":"真香啊！",
            "url":"/media/sounds/.mp3_scKzIcl",
            "id":206
         },
         {
            "name":"たのし～",
            "url":"/media/sounds/.mp3_5uTg6Ju",
            "id":207
         },
         {
            "name":"你好壞喔",
            "url":"/media/sounds/.mp3_Wmq5JOP",
            "id":208
         },
         {
            "name":"你這樣對嗎？",
            "url":"/media/sounds/.mp3_wTOuu4G",
            "id":209
         },
         {
            "name":"我要多穿兩條內褲",
            "url":"/media/sounds/.mp3_T2RwEiC",
            "id":210
         },
         {
            "name":"濕寶～",
            "url":"/media/sounds/.mp3_TlXemTV",
            "id":211
         },
         {
            "name":"猴塞雷啊",
            "url":"/media/sounds/.mp3_WqgyN9r",
            "id":212
         },
         {
            "name":"我把我動產不動產家屁眼全賣了",
            "url":"/media/sounds/.mp3_4EAgDOQ",
            "id":213
         },
         {
            "name":"兆元笑",
            "url":"/media/sounds/.mp3_HzEUCWM",
            "id":214
         },
         {
            "name":"我怎麼可能這麼做啊！",
            "url":"/media/sounds/.mp3_tEq1Kr4",
            "id":215
         },
         {
            "name":"我要幫你改運了喔",
            "url":"/media/sounds/.mp3_9VRSqMg",
            "id":216
         },
         {
            "name":"你醒啦",
            "url":"/media/sounds/.mp3_tQmi6hn",
            "id":217
         },
         {
            "name":"哎呦！你醒啦～",
            "url":"/media/sounds/.mp3_EqDC0c7",
            "id":218
         },
         {
            "name":"HappyBirthday",
            "url":"/media/sounds/happy-birthday_XLXSzYR.mp3",
            "id":219
         },
         {
            "name":"所有人都是我老婆",
            "url":"/media/sounds/.mp3_sbj994Y",
            "id":220
         },
         {
            "name":"怎麼變這麼婆這麼漂亮啊",
            "url":"/media/sounds/.mp3_bBgDhny",
            "id":221
         },
         {
            "name":"天地最強宇宙真理",
            "url":"/media/sounds/.mp3_pf1EKSO",
            "id":222
         },
         {
            "name":"哎呀～我眼睛業障重啊～",
            "url":"/media/sounds/.mp3_FNsal5K",
            "id":223
         },
         {
            "name":"啊啊～好棒！",
            "url":"/media/sounds/.mp3_2Pf6ty4",
            "id":224
         },
         {
            "name":"幹太棒了吧！",
            "url":"/media/sounds/.mp3_9shXRMQ",
            "id":225
         },
         {
            "name":"放開我啊～",
            "url":"/media/sounds/.mp3_DkRpadZ",
            "id":226
         },
         {
            "name":"小孩子才做選擇",
            "url":"/media/sounds/.mp3_T2K3Tyu",
            "id":227
         },
         {
            "name":"我全要",
            "url":"/media/sounds/.mp3_tYxrJKZ",
            "id":228
         },
         {
            "name":"等一下好好去房間調教調教你",
            "url":"/media/sounds/.mp3_1zWRMoS",
            "id":229
         },
         {
            "name":"謀啦～",
            "url":"/media/sounds/.mp3_a3v7rwf",
            "id":230
         },
         {
            "name":"只不過是個",
            "url":"/media/sounds/.mp3_A6IHG8S",
            "id":231
         },
         {
            "name":"你知道",
            "url":"/media/sounds/.mp3_9lU2pXz",
            "id":232
         },
         {
            "name":"什麼叫做",
            "url":"/media/sounds/.mp3_5FA9OZX",
            "id":233
         },
         {
            "name":"我的",
            "url":"/media/sounds/.mp3_E4jgfeU",
            "id":234
         },
         {
            "name":"味道",
            "url":"/media/sounds/.mp3_y8SNd88",
            "id":235
         },
         {
            "name":"嗎",
            "url":"/media/sounds/.mp3_vqxkMtX",
            "id":236
         },
         {
            "name":"蛤？",
            "url":"/media/sounds/.mp3_o1rNToO",
            "id":237
         },
         {
            "name":"在皮一點我就讓你晚上知道",
            "url":"/media/sounds/.mp3_rtzPJja",
            "id":238
         },
         {
            "name":"是怎樣啊",
            "url":"/media/sounds/.mp3_zO8brI2",
            "id":239
         },
         {
            "name":"我是瘟神嗎？",
            "url":"/media/sounds/.mp3_uBnLvz5",
            "id":240
         },
         {
            "name":"桌子底下",
            "url":"/media/sounds/.mp3_CXt5AG7",
            "id":241
         },
         {
            "name":"起來一下",
            "url":"/media/sounds/.mp3_UNGUHko",
            "id":242
         },
         {
            "name":"叫你啊",
            "url":"/media/sounds/.mp3_ivKY1ab",
            "id":243
         },
         {
            "name":"好不好",
            "url":"/media/sounds/.mp3_zBn6ZhZ",
            "id":244
         },
         {
            "name":"什麼歌？",
            "url":"/media/sounds/.mp3_9Sx3Fi1",
            "id":245
         },
         {
            "name":"哪➚尼➚",
            "url":"/media/sounds/.mp3_NXAg8RW",
            "id":246
         },
         {
            "name":"這麼牛逼的嗎？",
            "url":"/media/sounds/.mp3_FYwiWr9",
            "id":247
         },
         {
            "name":"把",
            "url":"/media/sounds/.mp3_ym1NvBp",
            "id":307
         },
         {
            "name":"這什麼鬼東西啊？",
            "url":"/media/sounds/.mp3_pqVCbPO",
            "id":309
         },
         {
            "name":"太可怕了吧",
            "url":"/media/sounds/.mp3_wEaxE9L",
            "id":310
         },
         {
            "name":"好了沒啊？",
            "url":"/media/sounds/.mp3_BW6tyTT",
            "id":314
         },
         {
            "name":"上新聞囉",
            "url":"/media/sounds/.mp3_gPPcUjD",
            "id":317
         },
         {
            "name":"什麼時候",
            "url":"/media/sounds/.mp3_ObQ0FfC",
            "id":324
         },
         {
            "name":"尷尬",
            "url":"/media/sounds/.mp3_HklRQsG",
            "id":325
         },
         {
            "name":"怎麼辦啊？",
            "url":"/media/sounds/.mp3_qlgqmfn",
            "id":328
         },
         {
            "name":"是",
            "url":"/media/sounds/.mp3_IqIZ9bz",
            "id":329
         },
         {
            "name":"爺",
            "url":"/media/sounds/.mp3_U8MulLt",
            "id":331
         },
         {
            "name":"happy",
            "url":"/media/sounds/happy_spBjEL2.mp3",
            "id":336
         },
         {
            "name":"你怎麼又來啦？",
            "url":"/media/sounds/.mp3_TnSzYq3",
            "id":341
         },
         {
            "name":"不懂",
            "url":"/media/sounds/.mp3_Fr1tQKO",
            "id":342
         },
         {
            "name":"有你",
            "url":"/media/sounds/.mp3_LzB3kFN",
            "id":343
         },
         {
            "name":"我又來啦",
            "url":"/media/sounds/.mp3_JF61IwS",
            "id":344
         },
         {
            "name":"還是你",
            "url":"/media/sounds/.mp3_AA0DJBc",
            "id":345
         },
         {
            "name":"你",
            "url":"/media/sounds/.mp3_9dQkvUH",
            "id":346
         },
         {
            "name":"我",
            "url":"/media/sounds/.mp3_sogc0gA",
            "id":347
         },
         {
            "name":"哎呀",
            "url":"/media/sounds/.mp3_Bxmlmwg",
            "id":348
         },
         {
            "name":"你怎麼頭斷掉了？",
            "url":"/media/sounds/.mp3_ujPdEAK",
            "id":353
         },
         {
            "name":"你不是說好要陪我一輩子？",
            "url":"/media/sounds/.mp3_Mhj70or",
            "id":354
         },
         {
            "name":"渣男",
            "url":"/media/sounds/.mp3_i4gx9Gk",
            "id":355
         },
         {
            "name":"灰飛煙滅",
            "url":"/media/sounds/.mp3_IR2CtHE",
            "id":359
         },
         {
            "name":"太慘烈的吧",
            "url":"/media/sounds/.mp3_sLiZBX2",
            "id":360
         },
         {
            "name":"你要幹嗎？",
            "url":"/media/sounds/.mp3_bydkG1V",
            "id":364
         },
         {
            "name":"先生",
            "url":"/media/sounds/.mp3_AeW95MZ",
            "id":365
         },
         {
            "name":"新年快樂",
            "url":"/media/sounds/.mp3_MbsrVzY",
            "id":379
         },
         {
            "name":"咱們要統一啦",
            "url":"/media/sounds/.mp3_QgCdCyg",
            "id":380
         },
         {
            "name":"不要",
            "url":"/media/sounds/.mp3_IHsU4pG",
            "id":383
         },
         {
            "name":"你不要靠近我蟑螂我錯了",
            "url":"/media/sounds/.mp3_mrrAtl3",
            "id":384
         },
         {
            "name":"是2",
            "url":"/media/sounds/.mp3_5nCbp4v",
            "id":385
         },
         {
            "name":"大便",
            "url":"/media/sounds/.mp3_4G0urzv",
            "id":386
         },
         {
            "name":"你他媽",
            "url":"/media/sounds/.mp3_XPCFXuS",
            "id":387
         },
         {
            "name":"不得了了",
            "url":"/media/sounds/.mp3_Qn9pWYR",
            "id":388
         },
         {
            "name":"出大事了",
            "url":"/media/sounds/.mp3_9YPR0ov",
            "id":389
         },
         {
            "name":"一模一樣",
            "url":"/media/sounds/.mp3_kk7WSG5",
            "id":390
         },
         {
            "name":"超可怕的",
            "url":"/media/sounds/.mp3_0kGDWLR",
            "id":391
         },
         {
            "name":"中華民國萬歲",
            "url":"/media/sounds/.mp3_ZmHJ10j",
            "id":393
         },
         {
            "name":"這什麼啊？",
            "url":"/media/sounds/.mp3_1HRKVPW",
            "id":394
         },
         {
            "name":"哇靠！",
            "url":"/media/sounds/.mp3_aJHSwOW",
            "id":395
         },
         {
            "name":"太屌了吧！",
            "url":"/media/sounds/.mp3_Omn0ZtX",
            "id":396
         },
         {
            "name":"這三小啊？",
            "url":"/media/sounds/.mp3_k8konf2",
            "id":397
         },
         {
            "name":"出事了",
            "url":"/media/sounds/.mp3_3Ro8AvH",
            "id":398
         },
         {
            "name":"阿伯",
            "url":"/media/sounds/.mp3_ps6pmDv",
            "id":399
         },
         {
            "name":"深入淺出",
            "url":"/media/sounds/.mp3_FDcfxNo",
            "id":401
         },
         {
            "name":"生產順利",
            "url":"/media/sounds/.mp3_cxwzayb",
            "id":403
         },
         {
            "name":"急救一下",
            "url":"/media/sounds/.mp3_1Z1Xnfm",
            "id":404
         },
         {
            "name":"台北",
            "url":"/media/sounds/.mp3_Y494UYs",
            "id":434
         },
         {
            "name":"忠孝東路",
            "url":"/media/sounds/.mp3_LBXz6uL",
            "id":435
         },
         {
            "name":"結果",
            "url":"/media/sounds/.mp3_RU5oqMj",
            "id":437
         },
         {
            "name":"說",
            "url":"/media/sounds/.mp3_BpwjgNO",
            "id":438
         },
         {
            "name":"觀落陰",
            "url":"/media/sounds/.mp3_TvwyYhR",
            "id":444
         },
         {
            "name":"通靈",
            "url":"/media/sounds/.mp3_qSlqUFK",
            "id":445
         },
         {
            "name":"在",
            "url":"/media/sounds/.mp3_qQgFOBk",
            "id":450
         },
         {
            "name":"你吐啊",
            "url":"/media/sounds/.mp3_zG1BCka",
            "id":452
         },
         {
            "name":"蹦",
            "url":"/media/sounds/.mp3_XMzQuxK",
            "id":457
         },
         {
            "name":"決鬥",
            "url":"/media/sounds/.mp3_pWOhlpL",
            "id":458
         },
         {
            "name":"三十五塊",
            "url":"/media/sounds/.mp3_rHctmOg",
            "id":459
         },
         {
            "name":"水蜜桃",
            "url":"/media/sounds/.mp3_OSS7bvz",
            "id":460
         },
         {
            "name":"三百塊",
            "url":"/media/sounds/.mp3_pFTJkxN",
            "id":461
         },
         {
            "name":"芭樂",
            "url":"/media/sounds/.mp3_YzwyywO",
            "id":462
         },
         {
            "name":"三十塊",
            "url":"/media/sounds/.mp3_QGiK44J",
            "id":463
         },
         {
            "name":"謀啦～2",
            "url":"/media/sounds/2_oZvzslY.mp3",
            "id":464
         },
         {
            "name":"拳頭",
            "url":"/media/sounds/.mp3_QlUfR8t",
            "id":494
         },
         {
            "name":"爸爸",
            "url":"/media/sounds/.mp3_wpFdGs2",
            "id":495
         },
         {
            "name":"公仔",
            "url":"/media/sounds/.mp3_e9j61JF",
            "id":496
         },
         {
            "name":"跟著",
            "url":"/media/sounds/.mp3_3e6ZBYm",
            "id":497
         },
         {
            "name":"那我會",
            "url":"/media/sounds/.mp3_gmArQb2",
            "id":498
         },
         {
            "name":"去夢裡面",
            "url":"/media/sounds/.mp3_coh49O5",
            "id":499
         },
         {
            "name":"讓你知道",
            "url":"/media/sounds/.mp3_gAdXc3U",
            "id":500
         },
         {
            "name":"誰才是",
            "url":"/media/sounds/.mp3_JkcDmRO",
            "id":501
         },
         {
            "name":"老大",
            "url":"/media/sounds/.mp3_Trwe1qB",
            "id":502
         }
      ]
   },
   {
      "name":"嘎抓",
      "datas":[
         {
            "name":"嘎抓打呼",
            "url":"/media/sounds/1_RxbUSue.mp3",
            "id":248
         },
         {
            "name":"嘎抓：幹你娘",
            "url":"/media/sounds/.mp3_GjxolX3",
            "id":249
         },
         {
            "name":"嘎抓：哭啊！",
            "url":"/media/sounds/.mp3_uTV0SgR",
            "id":250
         },
         {
            "name":"嘎抓：大濕不讓我睡",
            "url":"/media/sounds/.mp3_kF8jAih",
            "id":251
         },
         {
            "name":"嘎抓：晚上只好跟大濕睡",
            "url":"/media/sounds/.mp3_TkV8jZD",
            "id":252
         },
         {
            "name":"嘎抓：我是甲",
            "url":"/media/sounds/22_c7ccMHg.mp3",
            "id":253
         },
         {
            "name":"嘎抓：阿偉阿偉",
            "url":"/media/sounds/.mp3_wErZH4e",
            "id":254
         },
         {
            "name":"嘎抓：大濕屁眼會咬人",
            "url":"/media/sounds/.mp3_8DmmgHn",
            "id":255
         },
         {
            "name":"嘎抓：哇操",
            "url":"/media/sounds/.mp3_HYy5DzO",
            "id":256
         },
         {
            "name":"嘎抓：皮卡屁",
            "url":"/media/sounds/.mp3_J897yVm",
            "id":257
         },
         {
            "name":"嘎抓：不要在肛了",
            "url":"/media/sounds/.mp3_olO5X0N",
            "id":258
         },
         {
            "name":"嘎抓：輕一點",
            "url":"/media/sounds/.mp3_QnNGMFq",
            "id":259
         },
         {
            "name":"嘎抓：啊➚～",
            "url":"/media/sounds/.mp3_fkpe546",
            "id":260
         },
         {
            "name":"嘎抓：啊➚～～",
            "url":"/media/sounds/.mp3_bu8GFyv",
            "id":261
         },
         {
            "name":"嘎抓：『嘎抓不是會脫窗的人』",
            "url":"/media/sounds/.mp3_uA48kwL",
            "id":262
         },
         {
            "name":"嘎抓：『啊啊啊～』",
            "url":"/media/sounds/.mp3_GZFizCd",
            "id":263
         },
         {
            "name":"嘎抓：『睡到脫肛』",
            "url":"/media/sounds/.mp3_Nm0zWnN",
            "id":264
         },
         {
            "name":"嘎抓：『YA～』",
            "url":"/media/sounds/ya_wCoZNji.mp3",
            "id":265
         },
         {
            "name":"嘎抓：『好耶～』",
            "url":"/media/sounds/.mp3_13lV1ef",
            "id":266
         },
         {
            "name":"嘎抓：『我最喜歡睡覺了～』",
            "url":"/media/sounds/.mp3_cZF35G5",
            "id":267
         },
         {
            "name":"嘎抓：『大家好我是嘎抓』",
            "url":"/media/sounds/.mp3_DY0avBP",
            "id":268
         },
         {
            "name":"嘎抓：『好爛喔』",
            "url":"/media/sounds/.mp3_P5fcwfI",
            "id":269
         },
         {
            "name":"嘎抓：『什麼垃圾東西啊？』",
            "url":"/media/sounds/.mp3_3JCSP0p",
            "id":270
         },
         {
            "name":"嘎抓：『好想過去給你肛喔』",
            "url":"/media/sounds/.mp3_51pWKeR",
            "id":271
         },
         {
            "name":"嘎抓打哈欠",
            "url":"/media/sounds/.mp3_bad7QgK",
            "id":272
         },
         {
            "name":"嘎抓：『謝謝喔～』",
            "url":"/media/sounds/.mp3_SXTZPPk",
            "id":273
         },
         {
            "name":"嘎抓：『歡迎來我頻道訂閱我喔～YA～』",
            "url":"/media/sounds/ya_GtcXMc0.mp3",
            "id":274
         },
         {
            "name":"嘎抓：B打開",
            "url":"/media/sounds/b_oyzGb08.mp3",
            "id":275
         },
         {
            "name":"嘎抓：『我講B打開感覺好色』",
            "url":"/media/sounds/b_yA806v0.mp3",
            "id":276
         },
         {
            "name":"嘎抓：『感都是用肺換來的』",
            "url":"/media/sounds/.mp3_oObkOG5",
            "id":277
         },
         {
            "name":"嘎抓：『嗨大好我是小嘎』",
            "url":"/media/sounds/.mp3_AJZNYxW",
            "id":278
         },
         {
            "name":"嘎抓：『呱』",
            "url":"/media/sounds/.mp3_7CYURUm",
            "id":279
         },
         {
            "name":"嘎抓：『來跟妹子說早安嘍』",
            "url":"/media/sounds/.mp3_90yldZh",
            "id":280
         },
         {
            "name":"嘎抓：『給你吃點好吃的呦』",
            "url":"/media/sounds/.mp3_xrBlhwx",
            "id":281
         },
         {
            "name":"嘎抓：『襙你嗎的』",
            "url":"/media/sounds/.mp3_AkIrk09",
            "id":282
         },
         {
            "name":"嘎抓：『皮皮』",
            "url":"/media/sounds/.mp3_Hrl5G1l",
            "id":283
         },
         {
            "name":"嘎抓：『我愛的人是皮卡屁』",
            "url":"/media/sounds/.mp3_Q8vbOIq",
            "id":284
         },
         {
            "name":"嘎抓出來了",
            "url":"/media/sounds/.mp3_lqERbh3",
            "id":285
         },
         {
            "name":"嘎抓：『垃圾』",
            "url":"/media/sounds/.mp3_EMoDSJy",
            "id":503
         }
      ]
   }
];