var audios = [
   {
      "name":"人名",
      "datas":[
         {
            "name":"恭迎邱公建祥",
            "url":"/media/sounds/.mp3_Qvemr4N",
            "id":0
         },
         {
            "name":"哈鮭企鵝",
            "url":"/media/sounds/.mp3_7OLKGGO",
            "id":1
         },
         {
            "name":"嘎抓",
            "url":"/media/sounds/.mp3_R1pRA1t",
            "id":2
         },
         {
            "name":"兆元",
            "url":"/media/sounds/.mp3_zPEz9c6",
            "id":3
         },
         {
            "name":"小胖",
            "url":"/media/sounds/.mp3_QpwQt86",
            "id":4
         },
         {
            "name":"小胖2",
            "url":"/media/sounds/2_T68S1ZA.mp3",
            "id":5
         },
         {
            "name":"顯考邱公建祥",
            "url":"/media/sounds/.mp3_bJkmTFN",
            "id":6
         },
         {
            "name":"張兆元",
            "url":"/media/sounds/.mp3_XeWcKbg",
            "id":7
         },
         {
            "name":"邱少爺",
            "url":"/media/sounds/.mp3_ofbqNBN",
            "id":8
         },
         {
            "name":"顯考王公銘森哈鮭企鵝",
            "url":"/media/sounds/.mp3_amfgyo4",
            "id":9
         },
         {
            "name":"卓孝宣",
            "url":"/media/sounds/.mp3_qd0uQQo",
            "id":10
         },
         {
            "name":"馬老爺",
            "url":"/media/sounds/.mp3_IWq9iyu",
            "id":11
         },
         {
            "name":"邱建祥",
            "url":"/media/sounds/.mp3_s27gO7E",
            "id":12
         }
      ]
   },
   {
      "name":"升旗",
      "datas":[
         {
            "name":"主席",
            "url":"/media/sounds/.mp3_18G5w9A",
            "id":13
         },
         {
            "name":"下去啦～",
            "url":"/media/sounds/.mp3_DFdXjEP",
            "id":14
         },
         {
            "name":"哎呦～",
            "url":"/media/sounds/.mp3_QrtcPwQ",
            "id":15
         },
         {
            "name":"這就是我們的",
            "url":"/media/sounds/.mp3_8ymyDyI",
            "id":16
         },
         {
            "name":"即將啟航的時刻",
            "url":"/media/sounds/.mp3_HUEwc5Z",
            "id":17
         },
         {
            "name":"同志們",
            "url":"/media/sounds/.mp3_M7kUwsA",
            "id":18
         },
         {
            "name":"我們即將舉行升旗典禮",
            "url":"/media/sounds/.mp3_tUe2ygG",
            "id":19
         },
         {
            "name":"一柱清香",
            "url":"/media/sounds/.mp3_gxhPQkx",
            "id":20
         },
         {
            "name":"再上香",
            "url":"/media/sounds/.mp3_8RMm9J9",
            "id":21
         },
         {
            "name":"獻花獻果",
            "url":"/media/sounds/.mp3_zUXmqns",
            "id":22
         },
         {
            "name":"三柱清香罐頭塔我們送上去",
            "url":"/media/sounds/.mp3_BFReUrw",
            "id":23
         },
         {
            "name":"即將飛升為天",
            "url":"/media/sounds/.mp3_bVpSYKX",
            "id":24
         },
         {
            "name":"同志們請起立",
            "url":"/media/sounds/.mp3_ZSJifyG",
            "id":25
         },
         {
            "name":"在鞠躬的同時請脫帽",
            "url":"/media/sounds/.mp3_HfnwSCR",
            "id":26
         },
         {
            "name":"一鞠躬",
            "url":"/media/sounds/.mp3_VtDHyaY",
            "id":27
         },
         {
            "name":"再鞠躬",
            "url":"/media/sounds/.mp3_mbfQGeA",
            "id":28
         },
         {
            "name":"三鞠躬",
            "url":"/media/sounds/.mp3_Wcx0qm3",
            "id":29
         },
         {
            "name":"來賓與家屬打理",
            "url":"/media/sounds/.mp3_g2pyzTf",
            "id":30
         }
      ]
   },
   {
      "name":"罵人",
      "datas":[
         {
            "name":"屌你老母",
            "url":"/media/sounds/.mp3_MGgvnBc",
            "id":31
         },
         {
            "name":"看你娘",
            "url":"/media/sounds/.mp3_8dRNI8f",
            "id":32
         },
         {
            "name":"甲洨喔～",
            "url":"/media/sounds/.mp3_sezrMNa",
            "id":33
         },
         {
            "name":"靠杯喔",
            "url":"/media/sounds/.mp3_KE0u1go",
            "id":34
         },
         {
            "name":"欠我幹啊？是不是？",
            "url":"/media/sounds/.mp3_iCm5mfD",
            "id":35
         },
         {
            "name":"幹死他！",
            "url":"/media/sounds/.mp3_V90v3Uz",
            "id":36
         },
         {
            "name":"他死定了他",
            "url":"/media/sounds/.mp3_NNeVbQx",
            "id":37
         },
         {
            "name":"王八蛋",
            "url":"/media/sounds/.mp3_u5GyBfE",
            "id":38
         },
         {
            "name":"揍死你",
            "url":"/media/sounds/.mp3_eeRpk5h",
            "id":39
         },
         {
            "name":"你倒大楣了",
            "url":"/media/sounds/.mp3_k42Ebs9",
            "id":40
         },
         {
            "name":"你怎麼不下去啊？",
            "url":"/media/sounds/.mp3_ymzeXkq",
            "id":41
         },
         {
            "name":"你倒霉了",
            "url":"/media/sounds/.mp3_i7hzaxU",
            "id":42
         },
         {
            "name":"我沒有去幹他，我他媽不姓張！",
            "url":"/media/sounds/.mp3_EMspCZe",
            "id":43
         },
         {
            "name":"幹你娘G8",
            "url":"/media/sounds/g8.mp3",
            "id":44
         },
         {
            "name":"你有膽別跑幹你娘",
            "url":"/media/sounds/.mp3_Fr0dhay",
            "id":45
         },
         {
            "name":"操你媽啦",
            "url":"/media/sounds/.mp3_Q59LwK6",
            "id":46
         },
         {
            "name":"智障",
            "url":"/media/sounds/.mp3_GVdHujG",
            "id":47
         },
         {
            "name":"你媽死了",
            "url":"/media/sounds/nmsl.mp3",
            "id":48
         },
         {
            "name":"操你媽你叫誰啊",
            "url":"/media/sounds/.mp3_k7tgJCg",
            "id":49
         }
      ]
   },
   {
      "name":"叫聲",
      "datas":[
         {
            "name":"兆元高潮",
            "url":"/media/sounds/mp3cut_J0M19Kg.mp3",
            "id":50
         },
         {
            "name":"兆元高潮2",
            "url":"/media/sounds/.mp3_t3U7oFv",
            "id":51
         },
         {
            "name":"啊啊",
            "url":"/media/sounds/at88-cm-626466910-online-audio-converter-mp3cut.mp3",
            "id":52
         },
         {
            "name":"大濕嗩吶",
            "url":"/media/sounds/.mp3_pybTdjJ",
            "id":53
         },
         {
            "name":"汪",
            "url":"/media/sounds/.mp3_EBZyT3o",
            "id":54
         },
         {
            "name":"啊➚啊➚啊➚",
            "url":"/media/sounds/.mp3_kk0OzW9",
            "id":55
         },
         {
            "name":"埃～",
            "url":"/media/sounds/.mp3_f0EkltN",
            "id":56
         },
         {
            "name":"啵",
            "url":"/media/sounds/.mp3_MCgCt03",
            "id":57
         },
         {
            "name":"兆元的不明叫聲",
            "url":"/media/sounds/.mp3_bZZt709",
            "id":58
         },
         {
            "name":"兆元的不明叫聲2",
            "url":"/media/sounds/2_9UROs2b.mp3",
            "id":59
         },
         {
            "name":"啊～～～",
            "url":"/media/sounds/3_3aTyHtk.mp3",
            "id":60
         },
         {
            "name":"哇～",
            "url":"/media/sounds/.mp3_r3mRO9r",
            "id":61
         },
         {
            "name":"哇～～～",
            "url":"/media/sounds/.mp3_doUTf46",
            "id":62
         },
         {
            "name":"噢～～～",
            "url":"/media/sounds/.mp3_Yp43o6F",
            "id":63
         },
         {
            "name":"诶嘿～",
            "url":"/media/sounds/.mp3_LnaCDvj",
            "id":64
         }
      ]
   },
   {
      "name":"哭",
      "datas":[
         {
            "name":"元元子哭哭",
            "url":"/media/sounds/.mp3_vJDMfn5",
            "id":65
         },
         {
            "name":"元元子哭哭２",
            "url":"/media/sounds/2_qVIr1cb.mp3",
            "id":66
         },
         {
            "name":"嗚嗚嗚嗚嗚",
            "url":"/media/sounds/.mp3_62LU6K6",
            "id":67
         }
      ]
   },
   {
      "name":"小安",
      "datas":[
         {
            "name":"大家好，我是小安",
            "url":"/media/sounds/.mp3_cGYB7q3",
            "id":68
         },
         {
            "name":"我喜歡拉小提琴跳舞還有唱歌",
            "url":"/media/sounds/.mp3_0pHzSH8",
            "id":69
         },
         {
            "name":"如果喜歡歡迎來我的頻道",
            "url":"/media/sounds/.mp3_BbdP5Vn",
            "id":70
         }
      ]
   },
   {
      "name":"甲",
      "datas":[
         {
            "name":"幫他吸",
            "url":"/media/sounds/.mp3_XPMZXvO",
            "id":71
         },
         {
            "name":"蛤？乖乖站好啊！",
            "url":"/media/sounds/.mp3_6UcD4DW",
            "id":72
         },
         {
            "name":"又爽又舒服",
            "url":"/media/sounds/.mp3_GfRcuqk",
            "id":73
         },
         {
            "name":"衛浴設備",
            "url":"/media/sounds/.mp3_AQvH48g",
            "id":74
         },
         {
            "name":"只能在廁所",
            "url":"/media/sounds/.mp3_A4JmahD",
            "id":75
         },
         {
            "name":"馬桶",
            "url":"/media/sounds/.mp3_x7WYWqD",
            "id":76
         },
         {
            "name":"便器",
            "url":"/media/sounds/.mp3_aULw6kz",
            "id":77
         },
         {
            "name":"你們是Gay嗎？",
            "url":"/media/sounds/gay_hZMqOfW.mp3",
            "id":78
         },
         {
            "name":"我的台是Gay台",
            "url":"/media/sounds/gay_pnsVDVF.mp3",
            "id":79
         },
         {
            "name":"屁股人人有份",
            "url":"/media/sounds/.mp3_zcIbDje",
            "id":80
         },
         {
            "name":"禮到人到屁眼也到",
            "url":"/media/sounds/.mp3_JLFfEjh",
            "id":81
         },
         {
            "name":"幹到你屁眼流湯",
            "url":"/media/sounds/.mp3_7YZwjSV",
            "id":82
         },
         {
            "name":"等等來肛吧！",
            "url":"/media/sounds/.mp3_xgnrGrJ",
            "id":83
         },
         {
            "name":"屁眼故障來找我",
            "url":"/media/sounds/.mp3_MGfOnQ8",
            "id":84
         },
         {
            "name":"又粗又大又壯",
            "url":"/media/sounds/.mp3_pJiizp4",
            "id":85
         },
         {
            "name":"GayBar最佳員工",
            "url":"/media/sounds/gay-bar-mp3cut.mp3",
            "id":86
         },
         {
            "name":"正義比我大",
            "url":"/media/sounds/dfpid-lteg0-mp3cut.mp3",
            "id":87
         },
         {
            "name":"現在跟我已經特殊性關西了啦",
            "url":"/media/sounds/.mp3_m8XKsXq",
            "id":88
         },
         {
            "name":"你來當我男朋友好不好？",
            "url":"/media/sounds/.mp3_o0zKQGG",
            "id":89
         },
         {
            "name":"大大的",
            "url":"/media/sounds/.mp3_7iiP4Lt",
            "id":90
         },
         {
            "name":"更好用",
            "url":"/media/sounds/vid16109065234758.mp3",
            "id":91
         },
         {
            "name":"等你發現",
            "url":"/media/sounds/video-16109063368958.mp3",
            "id":92
         },
         {
            "name":"太大了",
            "url":"/media/sounds/.mp3_PFCfAH7",
            "id":93
         },
         {
            "name":"気持ちいい～～",
            "url":"/media/sounds/.mp3_Bg92T2V",
            "id":94
         },
         {
            "name":"小雞雞！",
            "url":"/media/sounds/.mp3_QD0ed1q",
            "id":95
         },
         {
            "name":"我愛的是皮卡屁",
            "url":"/media/sounds/.mp3_dHKsEEW",
            "id":96
         },
         {
            "name":"打手槍",
            "url":"/media/sounds/.mp3_zThDx90",
            "id":97
         },
         {
            "name":"臀部誘人的曲線",
            "url":"/media/sounds/.mp3_zd4cwBd",
            "id":98
         },
         {
            "name":"一見鐘䞍",
            "url":"/media/sounds/.mp3_3iMr8BA",
            "id":99
         },
         {
            "name":"你是我的屁眼～",
            "url":"/media/sounds/.mp3_YlLzldc",
            "id":100
         },
         {
            "name":"怎麼有東西黏黏的？",
            "url":"/media/sounds/.mp3_fXLtaS5",
            "id":101
         },
         {
            "name":"いたい いたい",
            "url":"/media/sounds/.mp3_2v23bZN",
            "id":102
         }
      ]
   },
   {
      "name":"其他",
      "datas":[
         {
            "name":"兆元你跪啊",
            "url":"/media/sounds/r_qgSILAC.mp3",
            "id":103
         },
         {
            "name":"我長得像盤子嗎",
            "url":"/media/sounds/mp3cut_GOBcLPW.mp3",
            "id":104
         },
         {
            "name":"男的幹",
            "url":"/media/sounds/nxx4t-vgzoo-mp3cut.mp3",
            "id":105
         },
         {
            "name":"好牛逼",
            "url":"/media/sounds/-firefox-nightly-2021-01-03-23-22-20-online-audio-converter-mp3cut.mp3",
            "id":106
         },
         {
            "name":"這...這什麼啊？",
            "url":"/media/sounds/.mp3_pwhUoDX",
            "id":107
         },
         {
            "name":"安安啊",
            "url":"/media/sounds/.mp3_Eiqk86r",
            "id":108
         },
         {
            "name":"來來來來來",
            "url":"/media/sounds/.mp3_xycGHnl",
            "id":109
         },
         {
            "name":"讓我看看",
            "url":"/media/sounds/.mp3_6Lqc3Qq",
            "id":110
         },
         {
            "name":"這真的可以做嗎？",
            "url":"/media/sounds/.mp3_4cS8Sjt",
            "id":111
         },
         {
            "name":"可以拉！沒問題啦！",
            "url":"/media/sounds/.mp3_J2YmRnC",
            "id":112
         },
         {
            "name":"や...やります！",
            "url":"/media/sounds/.mp3_QvZxuRG",
            "id":113
         },
         {
            "name":"這個房間",
            "url":"/media/sounds/.mp3_rwLYEP1",
            "id":114
         },
         {
            "name":"把門推開",
            "url":"/media/sounds/.mp3_H7oPwCo",
            "id":115
         },
         {
            "name":"亮亮的",
            "url":"/media/sounds/.mp3_QqnYLgm",
            "id":116
         },
         {
            "name":"真的要做嗎？",
            "url":"/media/sounds/.mp3_ZnEfHCY",
            "id":117
         },
         {
            "name":"你就做嘛！",
            "url":"/media/sounds/.mp3_j0R7stG",
            "id":118
         },
         {
            "name":"我回來啦！",
            "url":"/media/sounds/.mp3_wv5adop",
            "id":119
         },
         {
            "name":"到底是誰啦！",
            "url":"/media/sounds/.mp3_SNombcN",
            "id":120
         },
         {
            "name":"奇奇怪怪的",
            "url":"/media/sounds/id.mp3",
            "id":121
         },
         {
            "name":"變成大濕的形狀",
            "url":"/media/sounds/.mp3_GQGZwUg",
            "id":122
         },
         {
            "name":"按個讚",
            "url":"/media/sounds/.mp3_YMbw2s3",
            "id":123
         },
         {
            "name":"好可愛",
            "url":"/media/sounds/.mp3_0G9BCcf",
            "id":124
         },
         {
            "name":"好可愛喔～",
            "url":"/media/sounds/.mp3_FyLcYAA",
            "id":125
         },
         {
            "name":"車車",
            "url":"/media/sounds/.mp3_kKb2hld",
            "id":126
         },
         {
            "name":"戴綠帽",
            "url":"/media/sounds/.mp3_Yp1yG0w",
            "id":127
         },
         {
            "name":"不要幫我上香好嗎",
            "url":"/media/sounds/.mp3_nHwnfUq",
            "id":128
         },
         {
            "name":"PEKO",
            "url":"/media/sounds/peko_xlI32l1.mp3",
            "id":129
         },
         {
            "name":"我不知道",
            "url":"/media/sounds/.mp3_RARH3jm",
            "id":130
         },
         {
            "name":"那是什麼？",
            "url":"/media/sounds/.mp3_INOHvjM",
            "id":131
         },
         {
            "name":"我都不看這些的！",
            "url":"/media/sounds/.mp3_ghqhh7X",
            "id":132
         },
         {
            "name":"你餓了嗎？",
            "url":"/media/sounds/.mp3_V21onQI",
            "id":133
         },
         {
            "name":"給你吃點好吃的呦～",
            "url":"/media/sounds/.mp3_jgiFfID",
            "id":134
         },
         {
            "name":"什...什麼好吃的啊？",
            "url":"/media/sounds/.mp3_KPnGSI6",
            "id":135
         },
         {
            "name":"來啦！",
            "url":"/media/sounds/.mp3_EnLFMnS",
            "id":136
         },
         {
            "name":"拿...拿都拿！",
            "url":"/media/sounds/.mp3_SaVFyQg",
            "id":137
         },
         {
            "name":"元元要上車嗎？",
            "url":"/media/sounds/.mp3_OU5n2sn",
            "id":138
         },
         {
            "name":"不要了不要了不好意思不要了",
            "url":"/media/sounds/.mp3_n1abJfx",
            "id":139
         },
         {
            "name":"怕～",
            "url":"/media/sounds/.mp3_vv9syGt",
            "id":140
         },
         {
            "name":"獅子頭",
            "url":"/media/sounds/.mp3_8fd17HU",
            "id":141
         },
         {
            "name":"不要吵啊",
            "url":"/media/sounds/.mp3_p4StLDQ",
            "id":142
         },
         {
            "name":"等一下看了我就下去了",
            "url":"/media/sounds/.mp3_6ORMLw3",
            "id":143
         },
         {
            "name":"他在盯著我",
            "url":"/media/sounds/.mp3_GAXIdak",
            "id":144
         },
         {
            "name":"沒事沒事",
            "url":"/media/sounds/.mp3_dAnfP2k",
            "id":145
         },
         {
            "name":"我愛你",
            "url":"/media/sounds/.mp3_tD9ZK1A",
            "id":146
         },
         {
            "name":"咳瘦",
            "url":"/media/sounds/.mp3_bq1VpCh",
            "id":147
         },
         {
            "name":"是中邪了嗎？",
            "url":"/media/sounds/.mp3_ayGRwhA",
            "id":148
         },
         {
            "name":"是生病了",
            "url":"/media/sounds/.mp3_kFELYPV",
            "id":149
         },
         {
            "name":"變態",
            "url":"/media/sounds/.mp3_KFKQRfx",
            "id":150
         },
         {
            "name":"喂！",
            "url":"/media/sounds/.mp3_3KObnZ5",
            "id":151
         },
         {
            "name":"騎這麼快啊！",
            "url":"/media/sounds/.mp3_ci6BQit",
            "id":152
         },
         {
            "name":"被拖下去",
            "url":"/media/sounds/.mp3_XKnCheF",
            "id":153
         },
         {
            "name":"下車！",
            "url":"/media/sounds/.mp3_6XPkhEo",
            "id":154
         },
         {
            "name":"幹有這麼誇張的喔？",
            "url":"/media/sounds/.mp3_KE7boCw",
            "id":155
         },
         {
            "name":"哇幹！",
            "url":"/media/sounds/.mp3_rNYrWjw",
            "id":156
         },
         {
            "name":"真的要娶她了",
            "url":"/media/sounds/.mp3_mFo2yIu",
            "id":157
         },
         {
            "name":"好啦！",
            "url":"/media/sounds/.mp3_8twO2e8",
            "id":158
         },
         {
            "name":"決定了！",
            "url":"/media/sounds/.mp3_ziWarO0",
            "id":159
         },
         {
            "name":"辦婚禮了！",
            "url":"/media/sounds/.mp3_EwlEmLo",
            "id":160
         },
         {
            "name":"等著收我喜帖吧！",
            "url":"/media/sounds/.mp3_zGLOhn2",
            "id":161
         },
         {
            "name":"進入",
            "url":"/media/sounds/.mp3_UvcrPxx",
            "id":162
         },
         {
            "name":"鬼故事",
            "url":"/media/sounds/.mp3_cNcJ0vj",
            "id":163
         },
         {
            "name":"哭啊",
            "url":"/media/sounds/.mp3_0GIqxTc",
            "id":164
         },
         {
            "name":"屁眼",
            "url":"/media/sounds/.mp3_hD5HaDb",
            "id":165
         },
         {
            "name":"打開",
            "url":"/media/sounds/.mp3_RKWPHrR",
            "id":166
         },
         {
            "name":"為什麼是我的照片啊？",
            "url":"/media/sounds/.mp3_5zM5Wb0",
            "id":167
         },
         {
            "name":"厚呦又我",
            "url":"/media/sounds/.mp3_2expFUH",
            "id":168
         },
         {
            "name":"我要穿女裝",
            "url":"/media/sounds/.mp3_lus3V2U",
            "id":169
         },
         {
            "name":"衝了啦！",
            "url":"/media/sounds/.mp3_BfkAnRw",
            "id":170
         },
         {
            "name":"等一下",
            "url":"/media/sounds/.mp3_4wuO8Po",
            "id":171
         },
         {
            "name":"我不要！",
            "url":"/media/sounds/.mp3_7CVITIL",
            "id":172
         },
         {
            "name":"我好害怕",
            "url":"/media/sounds/.mp3_soEoCey",
            "id":173
         },
         {
            "name":"你就是我的妖豔賤貨",
            "url":"/media/sounds/.mp3_TKruUWZ",
            "id":174
         },
         {
            "name":"NO~~~",
            "url":"/media/sounds/no_hDCn8Pd.mp3",
            "id":175
         },
         {
            "name":"救我！",
            "url":"/media/sounds/.mp3_FpU85TY",
            "id":176
         },
         {
            "name":"龍潭廁所子",
            "url":"/media/sounds/.mp3_XBxAuQE",
            "id":177
         },
         {
            "name":"因該不會上車吧？",
            "url":"/media/sounds/.mp3_gbOQFSy",
            "id":178
         },
         {
            "name":"埃！埃！等一下等一下",
            "url":"/media/sounds/.mp3_DPvR6oE",
            "id":179
         },
         {
            "name":"嚇我一跳",
            "url":"/media/sounds/.mp3_17doqeq",
            "id":180
         },
         {
            "name":"呵呵！肥宅",
            "url":"/media/sounds/.mp3_3q4GehY",
            "id":181
         },
         {
            "name":"這不是我的衣服嗎？",
            "url":"/media/sounds/.mp3_tySaZ0Z",
            "id":182
         },
         {
            "name":"我好變那個肥宅",
            "url":"/media/sounds/.mp3_rrlF10B",
            "id":183
         },
         {
            "name":"我不想聽拜託不要告述我",
            "url":"/media/sounds/.mp3_vMfjpaV",
            "id":184
         },
         {
            "name":"我看你是很勇喔",
            "url":"/media/sounds/.mp3_AjtIw7J",
            "id":185
         },
         {
            "name":"你這個",
            "url":"/media/sounds/.mp3_v5SOpJW",
            "id":186
         },
         {
            "name":"NTR",
            "url":"/media/sounds/ntr.mp3",
            "id":187
         },
         {
            "name":"睡的真飽",
            "url":"/media/sounds/.mp3_MYL9vjd",
            "id":188
         },
         {
            "name":"怎麼那麼垃圾啊？",
            "url":"/media/sounds/.mp3_R15bTw4",
            "id":189
         },
         {
            "name":"什麼狀況？",
            "url":"/media/sounds/.mp3_n6fcv2s",
            "id":190
         },
         {
            "name":"不對啊",
            "url":"/media/sounds/.mp3_c3lKHdc",
            "id":191
         },
         {
            "name":"我哪是",
            "url":"/media/sounds/.mp3_AGeXdRj",
            "id":192
         },
         {
            "name":"我明明就是",
            "url":"/media/sounds/.mp3_30fUzjw",
            "id":193
         },
         {
            "name":"肥宅",
            "url":"/media/sounds/.mp3_g06gcfv",
            "id":194
         },
         {
            "name":"好色喔～",
            "url":"/media/sounds/.mp3_sQ6DrCY",
            "id":195
         },
         {
            "name":"啊！好香喔～",
            "url":"/media/sounds/.mp3_k9r6Iiu",
            "id":196
         },
         {
            "name":"怎麼那麼臭啊？",
            "url":"/media/sounds/.mp3_Bk1XvKF",
            "id":197
         },
         {
            "name":"我有這麼爛嗎？",
            "url":"/media/sounds/.mp3_EouyLCw",
            "id":198
         },
         {
            "name":"我要放屁了喔！",
            "url":"/media/sounds/.mp3_BodBvvP",
            "id":199
         },
         {
            "name":"盤子們",
            "url":"/media/sounds/.mp3_t3OdqKw",
            "id":200
         },
         {
            "name":"駕到啦～",
            "url":"/media/sounds/.mp3_WVK2kgt",
            "id":201
         },
         {
            "name":"乾我屁事啊？",
            "url":"/media/sounds/.mp3_HkNRBpr",
            "id":202
         },
         {
            "name":"好康的呦～",
            "url":"/media/sounds/.mp3_4xdu00P",
            "id":203
         },
         {
            "name":"哎呀～比遊戲還刺激～",
            "url":"/media/sounds/.mp3_ygUHrD1",
            "id":204
         },
         {
            "name":"自慰行助理",
            "url":"/media/sounds/.mp3_GDLviK8",
            "id":205
         },
         {
            "name":"真香啊！",
            "url":"/media/sounds/.mp3_scKzIcl",
            "id":206
         },
         {
            "name":"たのし～",
            "url":"/media/sounds/.mp3_5uTg6Ju",
            "id":207
         },
         {
            "name":"你好壞喔",
            "url":"/media/sounds/.mp3_Wmq5JOP",
            "id":208
         },
         {
            "name":"你這樣對嗎？",
            "url":"/media/sounds/.mp3_wTOuu4G",
            "id":209
         },
         {
            "name":"我要多穿兩條內褲",
            "url":"/media/sounds/.mp3_T2RwEiC",
            "id":210
         },
         {
            "name":"濕寶～",
            "url":"/media/sounds/.mp3_TlXemTV",
            "id":211
         },
         {
            "name":"猴塞雷啊",
            "url":"/media/sounds/.mp3_WqgyN9r",
            "id":212
         },
         {
            "name":"我把我動產不動產家屁眼全賣了",
            "url":"/media/sounds/.mp3_4EAgDOQ",
            "id":213
         },
         {
            "name":"兆元笑",
            "url":"/media/sounds/.mp3_HzEUCWM",
            "id":214
         },
         {
            "name":"我怎麼可能這麼做啊！",
            "url":"/media/sounds/.mp3_tEq1Kr4",
            "id":215
         },
         {
            "name":"我要幫你改運了喔",
            "url":"/media/sounds/.mp3_9VRSqMg",
            "id":216
         },
         {
            "name":"你醒啦",
            "url":"/media/sounds/.mp3_tQmi6hn",
            "id":217
         },
         {
            "name":"哎呦！你醒啦～",
            "url":"/media/sounds/.mp3_EqDC0c7",
            "id":218
         },
         {
            "name":"HappyBirthday",
            "url":"/media/sounds/happy-birthday_XLXSzYR.mp3",
            "id":219
         },
         {
            "name":"所有人都是我老婆",
            "url":"/media/sounds/.mp3_sbj994Y",
            "id":220
         },
         {
            "name":"怎麼變這麼婆這麼漂亮啊",
            "url":"/media/sounds/.mp3_bBgDhny",
            "id":221
         },
         {
            "name":"天地最強宇宙真理",
            "url":"/media/sounds/.mp3_pf1EKSO",
            "id":222
         },
         {
            "name":"哎呀～我眼睛業障重啊～",
            "url":"/media/sounds/.mp3_FNsal5K",
            "id":223
         },
         {
            "name":"啊啊～好棒！",
            "url":"/media/sounds/.mp3_2Pf6ty4",
            "id":224
         },
         {
            "name":"幹太棒了吧！",
            "url":"/media/sounds/.mp3_9shXRMQ",
            "id":225
         },
         {
            "name":"放開我啊～",
            "url":"/media/sounds/.mp3_DkRpadZ",
            "id":226
         },
         {
            "name":"小孩子才做選擇",
            "url":"/media/sounds/.mp3_T2K3Tyu",
            "id":227
         },
         {
            "name":"我全要",
            "url":"/media/sounds/.mp3_tYxrJKZ",
            "id":228
         },
         {
            "name":"等一下好好去房間調教調教你",
            "url":"/media/sounds/.mp3_1zWRMoS",
            "id":229
         },
         {
            "name":"謀啦～",
            "url":"/media/sounds/.mp3_a3v7rwf",
            "id":230
         },
         {
            "name":"只不過是個",
            "url":"/media/sounds/.mp3_A6IHG8S",
            "id":231
         },
         {
            "name":"你知道",
            "url":"/media/sounds/.mp3_9lU2pXz",
            "id":232
         },
         {
            "name":"什麼叫做",
            "url":"/media/sounds/.mp3_5FA9OZX",
            "id":233
         },
         {
            "name":"我的",
            "url":"/media/sounds/.mp3_E4jgfeU",
            "id":234
         },
         {
            "name":"味道",
            "url":"/media/sounds/.mp3_y8SNd88",
            "id":235
         },
         {
            "name":"嗎",
            "url":"/media/sounds/.mp3_vqxkMtX",
            "id":236
         },
         {
            "name":"蛤？",
            "url":"/media/sounds/.mp3_o1rNToO",
            "id":237
         },
         {
            "name":"在皮一點我就讓你晚上知道",
            "url":"/media/sounds/.mp3_rtzPJja",
            "id":238
         },
         {
            "name":"是怎樣啊",
            "url":"/media/sounds/.mp3_zO8brI2",
            "id":239
         },
         {
            "name":"我是瘟神嗎？",
            "url":"/media/sounds/.mp3_uBnLvz5",
            "id":240
         },
         {
            "name":"桌子底下",
            "url":"/media/sounds/.mp3_CXt5AG7",
            "id":241
         },
         {
            "name":"起來一下",
            "url":"/media/sounds/.mp3_UNGUHko",
            "id":242
         },
         {
            "name":"叫你啊",
            "url":"/media/sounds/.mp3_ivKY1ab",
            "id":243
         },
         {
            "name":"好不好",
            "url":"/media/sounds/.mp3_zBn6ZhZ",
            "id":244
         },
         {
            "name":"什麼歌？",
            "url":"/media/sounds/.mp3_9Sx3Fi1",
            "id":245
         },
         {
            "name":"哪➚尼➚",
            "url":"/media/sounds/.mp3_NXAg8RW",
            "id":246
         },
         {
            "name":"這麼牛逼的嗎？",
            "url":"/media/sounds/.mp3_FYwiWr9",
            "id":247
         }
      ]
   },
   {
      "name":"嘎抓",
      "datas":[
         {
            "name":"嘎抓打呼",
            "url":"/media/sounds/1_RxbUSue.mp3",
            "id":248
         },
         {
            "name":"嘎抓：幹你娘",
            "url":"/media/sounds/.mp3_GjxolX3",
            "id":249
         },
         {
            "name":"嘎抓：哭啊！",
            "url":"/media/sounds/.mp3_uTV0SgR",
            "id":250
         },
         {
            "name":"嘎抓：大濕不讓我睡",
            "url":"/media/sounds/.mp3_kF8jAih",
            "id":251
         },
         {
            "name":"嘎抓：晚上只好跟大濕睡",
            "url":"/media/sounds/.mp3_TkV8jZD",
            "id":252
         },
         {
            "name":"嘎抓：我是甲",
            "url":"/media/sounds/22_c7ccMHg.mp3",
            "id":253
         },
         {
            "name":"嘎抓：阿偉阿偉",
            "url":"/media/sounds/.mp3_wErZH4e",
            "id":254
         },
         {
            "name":"嘎抓：大濕屁眼會咬人",
            "url":"/media/sounds/.mp3_8DmmgHn",
            "id":255
         },
         {
            "name":"嘎抓：哇操",
            "url":"/media/sounds/.mp3_HYy5DzO",
            "id":256
         },
         {
            "name":"嘎抓：皮卡屁",
            "url":"/media/sounds/.mp3_J897yVm",
            "id":257
         },
         {
            "name":"嘎抓：不要在肛了",
            "url":"/media/sounds/.mp3_olO5X0N",
            "id":258
         },
         {
            "name":"嘎抓：輕一點",
            "url":"/media/sounds/.mp3_QnNGMFq",
            "id":259
         },
         {
            "name":"嘎抓：啊➚～",
            "url":"/media/sounds/.mp3_fkpe546",
            "id":260
         },
         {
            "name":"嘎抓：啊➚～～",
            "url":"/media/sounds/.mp3_bu8GFyv",
            "id":261
         },
         {
            "name":"嘎抓：『嘎抓不是會脫窗的人』",
            "url":"/media/sounds/.mp3_uA48kwL",
            "id":262
         },
         {
            "name":"嘎抓：『啊啊啊～』",
            "url":"/media/sounds/.mp3_GZFizCd",
            "id":263
         },
         {
            "name":"嘎抓：『睡到脫肛』",
            "url":"/media/sounds/.mp3_Nm0zWnN",
            "id":264
         },
         {
            "name":"嘎抓：『YA～』",
            "url":"/media/sounds/ya_wCoZNji.mp3",
            "id":265
         },
         {
            "name":"嘎抓：『好耶～』",
            "url":"/media/sounds/.mp3_13lV1ef",
            "id":266
         },
         {
            "name":"嘎抓：『我最喜歡睡覺了～』",
            "url":"/media/sounds/.mp3_cZF35G5",
            "id":267
         },
         {
            "name":"嘎抓：『大家好我是嘎抓』",
            "url":"/media/sounds/.mp3_DY0avBP",
            "id":268
         },
         {
            "name":"嘎抓：『好爛喔』",
            "url":"/media/sounds/.mp3_P5fcwfI",
            "id":269
         },
         {
            "name":"嘎抓：『什麼垃圾東西啊？』",
            "url":"/media/sounds/.mp3_3JCSP0p",
            "id":270
         },
         {
            "name":"嘎抓：『好想過去給你肛喔』",
            "url":"/media/sounds/.mp3_51pWKeR",
            "id":271
         },
         {
            "name":"嘎抓打哈欠",
            "url":"/media/sounds/.mp3_bad7QgK",
            "id":272
         },
         {
            "name":"嘎抓：『謝謝喔～』",
            "url":"/media/sounds/.mp3_SXTZPPk",
            "id":273
         },
         {
            "name":"嘎抓：『歡迎來我頻道訂閱我喔～YA～』",
            "url":"/media/sounds/ya_GtcXMc0.mp3",
            "id":274
         },
         {
            "name":"嘎抓：B打開",
            "url":"/media/sounds/b_oyzGb08.mp3",
            "id":275
         },
         {
            "name":"嘎抓：『我講B打開感覺好色』",
            "url":"/media/sounds/b_yA806v0.mp3",
            "id":276
         },
         {
            "name":"嘎抓：『感都是用肺換來的』",
            "url":"/media/sounds/.mp3_oObkOG5",
            "id":277
         },
         {
            "name":"嘎抓：『嗨大好我是小嘎』",
            "url":"/media/sounds/.mp3_AJZNYxW",
            "id":278
         },
         {
            "name":"嘎抓：『呱』",
            "url":"/media/sounds/.mp3_7CYURUm",
            "id":279
         },
         {
            "name":"嘎抓：『來跟妹子說早安嘍』",
            "url":"/media/sounds/.mp3_90yldZh",
            "id":280
         },
         {
            "name":"嘎抓：『給你吃點好吃的呦』",
            "url":"/media/sounds/.mp3_xrBlhwx",
            "id":281
         },
         {
            "name":"嘎抓：『襙你嗎的』",
            "url":"/media/sounds/.mp3_AkIrk09",
            "id":282
         },
         {
            "name":"嘎抓：『皮皮』",
            "url":"/media/sounds/.mp3_Hrl5G1l",
            "id":283
         },
         {
            "name":"嘎抓：『我愛的人是皮卡屁』",
            "url":"/media/sounds/.mp3_Q8vbOIq",
            "id":284
         },
         {
            "name":"嘎抓出來了",
            "url":"/media/sounds/.mp3_lqERbh3",
            "id":285
         }
      ]
   }
];